bash scripts/cross-domain/maste.sh all grocery 5 1 0
bash scripts/cross-domain/maste.sh fashion toy 3 2 0
bash scripts/cross-domain/maste.sh home pet 3 2 0
bash scripts/cross-domain/maste.sh fashion book 10 2 0
bash scripts/cross-domain/maste.sh home pet 20 0 0
bash scripts/cross-domain/maste.sh electronics book 3 3 0
bash scripts/cross-domain/maste.sh beauty book 20 2 0
bash scripts/cross-domain/maste.sh fashion toy 5 4 0
bash scripts/cross-domain/maste.sh fashion toy 5 1 0
bash scripts/cross-domain/maste.sh all toy 10 1 0
bash scripts/cross-domain/maste.sh beauty grocery 20 1 0
bash scripts/cross-domain/maste.sh fashion grocery 3 3 0
bash scripts/cross-domain/maste.sh beauty book 3 3 0
bash scripts/cross-domain/maste.sh electronics book 5 2 0
bash scripts/cross-domain/maste.sh all toy 3 0 0
bash scripts/cross-domain/maste.sh all toy 5 0 0
bash scripts/cross-domain/maste.sh fashion toy 1 0 0
bash scripts/cross-domain/maste.sh beauty pet 3 0 0
bash scripts/cross-domain/maste.sh electronics grocery 10 0 0
bash scripts/cross-domain/maste.sh all grocery 10 1 0
bash scripts/cross-domain/maste.sh electronics book 5 3 0
