bash scripts/cross-domain/maste.sh all pet 1 4 2
bash scripts/cross-domain/maste.sh all pet 3 2 2
bash scripts/cross-domain/maste.sh electronics grocery 3 1 2
bash scripts/cross-domain/maste.sh beauty toy 1 3 2
bash scripts/cross-domain/maste.sh fashion toy 10 4 2
bash scripts/cross-domain/maste.sh electronics book 20 3 2
bash scripts/cross-domain/maste.sh fashion toy 10 0 2
bash scripts/cross-domain/maste.sh all pet 1 2 2
bash scripts/cross-domain/maste.sh fashion pet 20 4 2
bash scripts/cross-domain/maste.sh all pet 3 4 2
bash scripts/cross-domain/maste.sh electronics toy 1 3 2
bash scripts/cross-domain/maste.sh electronics toy 1 2 2
bash scripts/cross-domain/maste.sh beauty grocery 5 1 2
bash scripts/cross-domain/maste.sh home toy 3 2 2
bash scripts/cross-domain/maste.sh electronics pet 1 3 2
bash scripts/cross-domain/maste.sh beauty toy 5 4 2
bash scripts/cross-domain/maste.sh electronics book 20 2 2
bash scripts/cross-domain/maste.sh home book 1 1 2
bash scripts/cross-domain/maste.sh all book 5 3 2
bash scripts/cross-domain/maste.sh electronics pet 5 2 2
bash scripts/cross-domain/maste.sh home book 10 1 2
