bash scripts/cross-domain/maste.sh all book 3 0 3
bash scripts/cross-domain/maste.sh electronics toy 1 0 3
bash scripts/cross-domain/maste.sh all book 5 2 3
bash scripts/cross-domain/maste.sh home book 10 2 3
bash scripts/cross-domain/maste.sh fashion book 1 0 3
bash scripts/cross-domain/maste.sh all book 10 1 3
bash scripts/cross-domain/maste.sh electronics pet 20 1 3
bash scripts/cross-domain/maste.sh electronics book 10 2 3
bash scripts/cross-domain/maste.sh all book 3 3 3
bash scripts/cross-domain/maste.sh electronics pet 1 2 3
bash scripts/cross-domain/maste.sh home pet 3 1 3
bash scripts/cross-domain/maste.sh all toy 20 0 3
bash scripts/cross-domain/maste.sh beauty book 20 4 3
bash scripts/cross-domain/maste.sh electronics toy 1 1 3
bash scripts/cross-domain/maste.sh beauty pet 20 0 3
bash scripts/cross-domain/maste.sh electronics grocery 10 2 3
bash scripts/cross-domain/maste.sh beauty toy 5 3 3
bash scripts/cross-domain/maste.sh fashion book 3 1 3
bash scripts/cross-domain/maste.sh home book 20 1 3
bash scripts/cross-domain/maste.sh all book 1 1 3
bash scripts/cross-domain/maste.sh fashion pet 3 3 3
