bash scripts/cross-domain/maste.sh home pet 1 1 5
bash scripts/cross-domain/maste.sh electronics pet 1 0 5
bash scripts/cross-domain/maste.sh electronics book 5 1 5
bash scripts/cross-domain/maste.sh all book 3 2 5
bash scripts/cross-domain/maste.sh beauty grocery 5 0 5
bash scripts/cross-domain/maste.sh fashion toy 3 4 5
bash scripts/cross-domain/maste.sh fashion toy 5 3 5
bash scripts/cross-domain/maste.sh fashion toy 3 1 5
bash scripts/cross-domain/maste.sh all book 10 0 5
bash scripts/cross-domain/maste.sh electronics toy 20 2 5
bash scripts/cross-domain/maste.sh home pet 5 4 5
bash scripts/cross-domain/maste.sh electronics pet 5 1 5
bash scripts/cross-domain/maste.sh home grocery 1 2 5
bash scripts/cross-domain/maste.sh electronics pet 20 0 5
bash scripts/cross-domain/maste.sh electronics toy 10 2 5
bash scripts/cross-domain/maste.sh beauty book 1 1 5
bash scripts/cross-domain/maste.sh home pet 5 3 5
bash scripts/cross-domain/maste.sh home grocery 5 2 5
bash scripts/cross-domain/maste.sh home grocery 20 1 5
bash scripts/cross-domain/maste.sh home toy 20 4 5
bash scripts/cross-domain/maste.sh beauty book 3 0 5
