bash scripts/cross-domain/maste.sh home toy 10 1 7
bash scripts/cross-domain/maste.sh electronics grocery 5 2 7
bash scripts/cross-domain/maste.sh fashion pet 10 3 7
bash scripts/cross-domain/maste.sh all pet 5 3 7
bash scripts/cross-domain/maste.sh fashion book 1 1 7
bash scripts/cross-domain/maste.sh beauty book 1 0 7
bash scripts/cross-domain/maste.sh home pet 3 4 7
bash scripts/cross-domain/maste.sh fashion toy 1 2 7
bash scripts/cross-domain/maste.sh beauty book 10 4 7
bash scripts/cross-domain/maste.sh all toy 5 1 7
bash scripts/cross-domain/maste.sh home pet 3 0 7
bash scripts/cross-domain/maste.sh home book 20 2 7
bash scripts/cross-domain/maste.sh beauty pet 1 1 7
bash scripts/cross-domain/maste.sh beauty toy 1 0 7
bash scripts/cross-domain/maste.sh electronics grocery 20 2 7
bash scripts/cross-domain/maste.sh beauty pet 1 3 7
bash scripts/cross-domain/maste.sh fashion toy 10 1 7
bash scripts/cross-domain/maste.sh fashion grocery 20 2 7
bash scripts/cross-domain/maste.sh fashion grocery 10 3 7
bash scripts/cross-domain/maste.sh home pet 20 2 7
bash scripts/cross-domain/maste.sh fashion pet 1 4 7
