bash scripts/cross-domain/maste.sh home book 3 2 3
bash scripts/cross-domain/maste.sh beauty grocery 3 3 3
bash scripts/cross-domain/maste.sh all book 5 4 3
bash scripts/cross-domain/maste.sh electronics grocery 3 3 3
bash scripts/cross-domain/maste.sh home book 10 4 3
bash scripts/cross-domain/maste.sh beauty pet 5 3 3
bash scripts/cross-domain/maste.sh home grocery 10 2 3
bash scripts/cross-domain/maste.sh home toy 20 2 3
bash scripts/cross-domain/maste.sh beauty grocery 20 2 3
bash scripts/cross-domain/maste.sh fashion grocery 10 4 3
bash scripts/cross-domain/maste.sh fashion grocery 1 1 3
bash scripts/cross-domain/maste.sh home grocery 1 4 3
bash scripts/cross-domain/maste.sh electronics book 20 1 3
bash scripts/cross-domain/maste.sh home toy 1 2 3
bash scripts/cross-domain/maste.sh beauty book 3 2 3
bash scripts/cross-domain/maste.sh home grocery 1 0 3
bash scripts/cross-domain/maste.sh home toy 5 3 3
bash scripts/cross-domain/maste.sh home pet 10 3 3
bash scripts/cross-domain/maste.sh beauty toy 5 0 3
bash scripts/cross-domain/maste.sh beauty pet 20 4 3
bash scripts/cross-domain/maste.sh all book 20 3 3
