bash scripts/cross-domain/maste.sh electronics pet 3 4 5
bash scripts/cross-domain/maste.sh electronics pet 3 0 5
bash scripts/cross-domain/maste.sh fashion grocery 5 3 5
bash scripts/cross-domain/maste.sh beauty pet 1 2 5
bash scripts/cross-domain/maste.sh electronics toy 20 3 5
bash scripts/cross-domain/maste.sh home book 1 2 5
bash scripts/cross-domain/maste.sh home book 5 2 5
bash scripts/cross-domain/maste.sh electronics book 10 3 5
bash scripts/cross-domain/maste.sh beauty toy 20 4 5
bash scripts/cross-domain/maste.sh fashion book 10 4 5
bash scripts/cross-domain/maste.sh electronics grocery 10 1 5
bash scripts/cross-domain/maste.sh fashion grocery 5 2 5
bash scripts/cross-domain/maste.sh electronics toy 10 1 5
bash scripts/cross-domain/maste.sh all toy 3 2 5
bash scripts/cross-domain/maste.sh beauty book 5 0 5
bash scripts/cross-domain/maste.sh all pet 1 0 5
bash scripts/cross-domain/maste.sh all toy 3 4 5
bash scripts/cross-domain/maste.sh fashion pet 1 1 5
bash scripts/cross-domain/maste.sh all book 20 0 5
bash scripts/cross-domain/maste.sh beauty grocery 5 4 5
