bash scripts/cross-domain/maste.sh all pet 1 1 3
bash scripts/cross-domain/maste.sh all book 20 1 3
bash scripts/cross-domain/maste.sh home book 20 0 3
bash scripts/cross-domain/maste.sh home pet 1 4 3
bash scripts/cross-domain/maste.sh all pet 10 3 3
bash scripts/cross-domain/maste.sh all grocery 5 3 3
bash scripts/cross-domain/maste.sh beauty grocery 1 1 3
bash scripts/cross-domain/maste.sh all pet 20 0 3
bash scripts/cross-domain/maste.sh home book 5 1 3
bash scripts/cross-domain/maste.sh electronics toy 3 2 3
bash scripts/cross-domain/maste.sh fashion grocery 1 0 3
bash scripts/cross-domain/maste.sh beauty book 5 2 3
bash scripts/cross-domain/maste.sh all pet 5 1 3
bash scripts/cross-domain/maste.sh fashion pet 10 0 3
bash scripts/cross-domain/maste.sh home book 3 4 3
bash scripts/cross-domain/maste.sh all toy 1 1 3
bash scripts/cross-domain/maste.sh home grocery 3 1 3
bash scripts/cross-domain/maste.sh fashion toy 3 3 3
bash scripts/cross-domain/maste.sh electronics book 3 0 3
bash scripts/cross-domain/maste.sh all toy 5 3 3
bash scripts/cross-domain/maste.sh fashion grocery 10 1 3
