bash scripts/cross-domain/maste.sh electronics book 1 4 5
bash scripts/cross-domain/maste.sh all pet 1 3 5
bash scripts/cross-domain/maste.sh all toy 1 2 5
bash scripts/cross-domain/maste.sh all toy 20 2 5
bash scripts/cross-domain/maste.sh all grocery 20 2 5
bash scripts/cross-domain/maste.sh electronics grocery 1 2 5
bash scripts/cross-domain/maste.sh fashion grocery 10 2 5
bash scripts/cross-domain/maste.sh fashion grocery 20 1 5
bash scripts/cross-domain/maste.sh fashion book 20 1 5
bash scripts/cross-domain/maste.sh electronics grocery 20 0 5
bash scripts/cross-domain/maste.sh electronics grocery 20 1 5
bash scripts/cross-domain/maste.sh beauty toy 5 2 5
bash scripts/cross-domain/maste.sh fashion book 5 0 5
bash scripts/cross-domain/maste.sh electronics book 3 4 5
bash scripts/cross-domain/maste.sh fashion pet 5 0 5
bash scripts/cross-domain/maste.sh all toy 20 4 5
bash scripts/cross-domain/maste.sh beauty grocery 5 2 5
bash scripts/cross-domain/maste.sh all pet 20 3 5
bash scripts/cross-domain/maste.sh electronics pet 10 3 5
bash scripts/cross-domain/maste.sh fashion toy 10 3 5
bash scripts/cross-domain/maste.sh all toy 10 3 5
