bash scripts/cross-domain/maste.sh beauty grocery 10 4 0
bash scripts/cross-domain/maste.sh all book 20 2 0
bash scripts/cross-domain/maste.sh beauty pet 3 3 0
bash scripts/cross-domain/maste.sh electronics grocery 5 1 0
bash scripts/cross-domain/maste.sh all grocery 10 4 0
bash scripts/cross-domain/maste.sh electronics pet 3 3 0
bash scripts/cross-domain/maste.sh electronics grocery 5 3 0
bash scripts/cross-domain/maste.sh beauty pet 10 4 0
bash scripts/cross-domain/maste.sh fashion pet 1 3 0
bash scripts/cross-domain/maste.sh home toy 1 0 0
bash scripts/cross-domain/maste.sh all grocery 3 4 0
bash scripts/cross-domain/maste.sh electronics grocery 20 4 0
bash scripts/cross-domain/maste.sh fashion toy 20 0 0
bash scripts/cross-domain/maste.sh beauty book 10 2 0
bash scripts/cross-domain/maste.sh home book 1 3 0
bash scripts/cross-domain/maste.sh all grocery 20 4 0
bash scripts/cross-domain/maste.sh beauty book 10 0 0
bash scripts/cross-domain/maste.sh electronics book 1 3 0
bash scripts/cross-domain/maste.sh fashion book 5 3 0
bash scripts/cross-domain/maste.sh all grocery 3 2 0
bash scripts/cross-domain/maste.sh fashion grocery 3 0 0
