bash scripts/cross-domain/dann/maste.sh home toy 5 4 1
bash scripts/cross-domain/dann/maste.sh electronics grocery 10 4 1
bash scripts/cross-domain/dann/maste.sh fashion book 5 2 1
bash scripts/cross-domain/dann/maste.sh beauty pet 5 0 1
bash scripts/cross-domain/dann/maste.sh all grocery 5 4 1
bash scripts/cross-domain/dann/maste.sh all grocery 5 0 1
bash scripts/cross-domain/dann/maste.sh beauty toy 3 4 1
bash scripts/cross-domain/dann/maste.sh beauty book 10 3 1
bash scripts/cross-domain/dann/maste.sh fashion book 20 3 1
bash scripts/cross-domain/dann/maste.sh all toy 20 1 1
bash scripts/cross-domain/dann/maste.sh electronics grocery 1 3 1
bash scripts/cross-domain/dann/maste.sh home toy 3 3 1
bash scripts/cross-domain/dann/maste.sh fashion book 20 0 1
bash scripts/cross-domain/dann/maste.sh all toy 1 4 1
bash scripts/cross-domain/dann/maste.sh fashion grocery 1 4 1
bash scripts/cross-domain/dann/maste.sh beauty pet 20 1 1
bash scripts/cross-domain/dann/maste.sh beauty toy 10 2 1
bash scripts/cross-domain/dann/maste.sh all grocery 20 0 1
bash scripts/cross-domain/dann/maste.sh all grocery 10 2 1
bash scripts/cross-domain/dann/maste.sh home toy 10 2 1
bash scripts/cross-domain/dann/maste.sh fashion pet 5 3 1
