bash scripts/cross-domain/dann/maste.sh all book 20 4 4
bash scripts/cross-domain/dann/maste.sh home pet 10 1 4
bash scripts/cross-domain/dann/maste.sh beauty toy 1 1 4
bash scripts/cross-domain/dann/maste.sh home book 5 4 4
bash scripts/cross-domain/dann/maste.sh home grocery 5 4 4
bash scripts/cross-domain/dann/maste.sh fashion pet 10 1 4
bash scripts/cross-domain/dann/maste.sh beauty grocery 20 4 4
bash scripts/cross-domain/dann/maste.sh fashion toy 20 4 4
bash scripts/cross-domain/dann/maste.sh electronics grocery 3 2 4
bash scripts/cross-domain/dann/maste.sh all grocery 1 4 4
bash scripts/cross-domain/dann/maste.sh electronics pet 10 4 4
bash scripts/cross-domain/dann/maste.sh beauty pet 10 0 4
bash scripts/cross-domain/dann/maste.sh all grocery 20 1 4
bash scripts/cross-domain/dann/maste.sh home toy 20 3 4
bash scripts/cross-domain/dann/maste.sh beauty toy 10 1 4
bash scripts/cross-domain/dann/maste.sh electronics pet 20 3 4
bash scripts/cross-domain/dann/maste.sh home toy 20 1 4
bash scripts/cross-domain/dann/maste.sh home pet 20 4 4
bash scripts/cross-domain/dann/maste.sh home toy 5 0 4
bash scripts/cross-domain/dann/maste.sh home toy 3 4 4
bash scripts/cross-domain/dann/maste.sh electronics pet 3 1 4
