bash scripts/cross-domain/dann/maste.sh beauty grocery 20 3 6
bash scripts/cross-domain/dann/maste.sh fashion pet 10 4 6
bash scripts/cross-domain/dann/maste.sh electronics grocery 5 4 6
bash scripts/cross-domain/dann/maste.sh electronics pet 5 4 6
bash scripts/cross-domain/dann/maste.sh all pet 5 4 6
bash scripts/cross-domain/dann/maste.sh fashion grocery 20 4 6
bash scripts/cross-domain/dann/maste.sh fashion book 5 4 6
bash scripts/cross-domain/dann/maste.sh fashion book 1 2 6
bash scripts/cross-domain/dann/maste.sh home toy 20 0 6
bash scripts/cross-domain/dann/maste.sh electronics book 3 1 6
bash scripts/cross-domain/dann/maste.sh electronics toy 3 3 6
bash scripts/cross-domain/dann/maste.sh all book 5 1 6
bash scripts/cross-domain/dann/maste.sh all pet 10 1 6
bash scripts/cross-domain/dann/maste.sh home toy 1 1 6
bash scripts/cross-domain/dann/maste.sh fashion pet 3 0 6
bash scripts/cross-domain/dann/maste.sh electronics grocery 10 3 6
bash scripts/cross-domain/dann/maste.sh all grocery 20 3 6
bash scripts/cross-domain/dann/maste.sh beauty toy 3 3 6
bash scripts/cross-domain/dann/maste.sh electronics toy 20 1 6
bash scripts/cross-domain/dann/maste.sh home book 1 0 6
bash scripts/cross-domain/dann/maste.sh electronics grocery 3 0 6
