bash scripts/cross-domain/dann/maste.sh beauty toy 10 4 0
bash scripts/cross-domain/dann/maste.sh all grocery 1 2 0
bash scripts/cross-domain/dann/maste.sh all grocery 1 1 0
bash scripts/cross-domain/dann/maste.sh beauty toy 10 0 0
bash scripts/cross-domain/dann/maste.sh all toy 10 4 0
bash scripts/cross-domain/dann/maste.sh all book 1 0 0
bash scripts/cross-domain/dann/maste.sh all book 10 3 0
bash scripts/cross-domain/dann/maste.sh electronics pet 3 2 0
bash scripts/cross-domain/dann/maste.sh electronics toy 5 3 0
bash scripts/cross-domain/dann/maste.sh beauty book 20 1 0
bash scripts/cross-domain/dann/maste.sh beauty grocery 5 3 0
bash scripts/cross-domain/dann/maste.sh fashion book 10 3 0
bash scripts/cross-domain/dann/maste.sh all pet 10 4 0
bash scripts/cross-domain/dann/maste.sh beauty pet 10 2 0
bash scripts/cross-domain/dann/maste.sh beauty book 3 4 0
bash scripts/cross-domain/dann/maste.sh all grocery 5 2 0
bash scripts/cross-domain/dann/maste.sh electronics book 5 4 0
bash scripts/cross-domain/dann/maste.sh fashion pet 20 0 0
bash scripts/cross-domain/dann/maste.sh electronics grocery 5 0 0
bash scripts/cross-domain/dann/maste.sh all book 1 4 0
bash scripts/cross-domain/dann/maste.sh all grocery 3 1 0
