bash scripts/cross-domain/dann/maste.sh all pet 3 1 1
bash scripts/cross-domain/dann/maste.sh fashion pet 1 0 1
bash scripts/cross-domain/dann/maste.sh beauty book 20 0 1
bash scripts/cross-domain/dann/maste.sh beauty grocery 20 0 1
bash scripts/cross-domain/dann/maste.sh home pet 5 2 1
bash scripts/cross-domain/dann/maste.sh beauty pet 10 3 1
bash scripts/cross-domain/dann/maste.sh all grocery 1 0 1
bash scripts/cross-domain/dann/maste.sh fashion pet 20 2 1
bash scripts/cross-domain/dann/maste.sh fashion book 10 0 1
bash scripts/cross-domain/dann/maste.sh all book 3 1 1
bash scripts/cross-domain/dann/maste.sh beauty grocery 10 0 1
bash scripts/cross-domain/dann/maste.sh all pet 10 0 1
bash scripts/cross-domain/dann/maste.sh home toy 10 3 1
bash scripts/cross-domain/dann/maste.sh all toy 3 3 1
bash scripts/cross-domain/dann/maste.sh electronics book 20 0 1
bash scripts/cross-domain/dann/maste.sh all toy 5 4 1
bash scripts/cross-domain/dann/maste.sh home grocery 5 3 1
bash scripts/cross-domain/dann/maste.sh beauty pet 20 2 1
bash scripts/cross-domain/dann/maste.sh home book 3 3 1
bash scripts/cross-domain/dann/maste.sh all toy 3 1 1
bash scripts/cross-domain/dann/maste.sh home grocery 1 1 1
