bash scripts/cross-domain/dann/maste.sh all pet 20 2 2
bash scripts/cross-domain/dann/maste.sh home pet 20 3 2
bash scripts/cross-domain/dann/maste.sh fashion pet 10 2 2
bash scripts/cross-domain/dann/maste.sh electronics grocery 3 4 2
bash scripts/cross-domain/dann/maste.sh beauty toy 20 3 2
bash scripts/cross-domain/dann/maste.sh home grocery 3 3 2
bash scripts/cross-domain/dann/maste.sh electronics book 10 1 2
bash scripts/cross-domain/dann/maste.sh fashion toy 20 2 2
bash scripts/cross-domain/dann/maste.sh beauty pet 5 1 2
bash scripts/cross-domain/dann/maste.sh home pet 20 1 2
bash scripts/cross-domain/dann/maste.sh all toy 1 0 2
bash scripts/cross-domain/dann/maste.sh beauty grocery 3 4 2
bash scripts/cross-domain/dann/maste.sh all book 1 2 2
bash scripts/cross-domain/dann/maste.sh electronics grocery 1 0 2
bash scripts/cross-domain/dann/maste.sh electronics book 1 2 2
bash scripts/cross-domain/dann/maste.sh beauty book 3 1 2
bash scripts/cross-domain/dann/maste.sh home book 10 0 2
bash scripts/cross-domain/dann/maste.sh all book 10 2 2
bash scripts/cross-domain/dann/maste.sh beauty pet 3 1 2
bash scripts/cross-domain/dann/maste.sh beauty toy 1 2 2
bash scripts/cross-domain/dann/maste.sh all pet 20 1 2
