bash scripts/cross-domain/dann/maste.sh fashion toy 10 2 2
bash scripts/cross-domain/dann/maste.sh fashion book 3 3 2
bash scripts/cross-domain/dann/maste.sh fashion grocery 5 0 2
bash scripts/cross-domain/dann/maste.sh all book 10 4 2
bash scripts/cross-domain/dann/maste.sh home grocery 20 4 2
bash scripts/cross-domain/dann/maste.sh fashion grocery 3 2 2
bash scripts/cross-domain/dann/maste.sh home grocery 1 3 2
bash scripts/cross-domain/dann/maste.sh all grocery 3 3 2
bash scripts/cross-domain/dann/maste.sh beauty grocery 1 4 2
bash scripts/cross-domain/dann/maste.sh beauty grocery 1 3 2
bash scripts/cross-domain/dann/maste.sh fashion grocery 1 3 2
bash scripts/cross-domain/dann/maste.sh home book 3 1 2
bash scripts/cross-domain/dann/maste.sh fashion toy 5 2 2
bash scripts/cross-domain/dann/maste.sh all pet 20 4 2
bash scripts/cross-domain/dann/maste.sh beauty book 10 1 2
bash scripts/cross-domain/dann/maste.sh home book 5 3 2
bash scripts/cross-domain/dann/maste.sh fashion pet 20 3 2
bash scripts/cross-domain/dann/maste.sh home toy 5 2 2
bash scripts/cross-domain/dann/maste.sh fashion toy 1 3 2
bash scripts/cross-domain/dann/maste.sh electronics toy 10 4 2
bash scripts/cross-domain/dann/maste.sh electronics book 20 4 2
