bash scripts/cross-domain/dann/maste.sh beauty pet 10 1 4
bash scripts/cross-domain/dann/maste.sh beauty toy 3 2 4
bash scripts/cross-domain/dann/maste.sh all toy 10 2 4
bash scripts/cross-domain/dann/maste.sh home pet 10 2 4
bash scripts/cross-domain/dann/maste.sh home grocery 10 4 4
bash scripts/cross-domain/dann/maste.sh home book 1 4 4
bash scripts/cross-domain/dann/maste.sh fashion grocery 20 3 4
bash scripts/cross-domain/dann/maste.sh fashion grocery 1 2 4
bash scripts/cross-domain/dann/maste.sh all toy 20 3 4
bash scripts/cross-domain/dann/maste.sh home toy 10 4 4
bash scripts/cross-domain/dann/maste.sh all pet 10 2 4
bash scripts/cross-domain/dann/maste.sh beauty grocery 10 1 4
bash scripts/cross-domain/dann/maste.sh home grocery 3 0 4
bash scripts/cross-domain/dann/maste.sh electronics grocery 1 1 4
bash scripts/cross-domain/dann/maste.sh electronics pet 5 0 4
bash scripts/cross-domain/dann/maste.sh beauty grocery 1 2 4
bash scripts/cross-domain/dann/maste.sh beauty pet 5 2 4
bash scripts/cross-domain/dann/maste.sh home pet 1 2 4
bash scripts/cross-domain/dann/maste.sh beauty book 1 2 4
bash scripts/cross-domain/dann/maste.sh electronics grocery 20 3 4
