bash scripts/cross-domain/dann/maste.sh home grocery 20 3 6
bash scripts/cross-domain/dann/maste.sh home toy 3 1 6
bash scripts/cross-domain/dann/maste.sh fashion book 1 4 6
bash scripts/cross-domain/dann/maste.sh beauty pet 1 0 6
bash scripts/cross-domain/dann/maste.sh electronics toy 3 4 6
bash scripts/cross-domain/dann/maste.sh fashion pet 5 4 6
bash scripts/cross-domain/dann/maste.sh home toy 1 3 6
bash scripts/cross-domain/dann/maste.sh electronics book 3 2 6
bash scripts/cross-domain/dann/maste.sh fashion book 20 2 6
bash scripts/cross-domain/dann/maste.sh electronics toy 10 0 6
bash scripts/cross-domain/dann/maste.sh all book 5 0 6
bash scripts/cross-domain/dann/maste.sh beauty toy 20 1 6
bash scripts/cross-domain/dann/maste.sh beauty grocery 3 2 6
bash scripts/cross-domain/dann/maste.sh all pet 5 2 6
bash scripts/cross-domain/dann/maste.sh home toy 3 0 6
bash scripts/cross-domain/dann/maste.sh home grocery 3 4 6
bash scripts/cross-domain/dann/maste.sh fashion toy 5 0 6
bash scripts/cross-domain/dann/maste.sh home grocery 20 2 6
bash scripts/cross-domain/dann/maste.sh home grocery 5 0 6
bash scripts/cross-domain/dann/maste.sh beauty toy 1 4 6
