bash scripts/cross-domain/dann/maste.sh all toy 10 0 7
bash scripts/cross-domain/dann/maste.sh beauty book 5 4 7
bash scripts/cross-domain/dann/maste.sh electronics book 1 0 7
bash scripts/cross-domain/dann/maste.sh electronics pet 1 1 7
bash scripts/cross-domain/dann/maste.sh electronics toy 1 4 7
bash scripts/cross-domain/dann/maste.sh fashion book 3 0 7
bash scripts/cross-domain/dann/maste.sh electronics toy 5 2 7
bash scripts/cross-domain/dann/maste.sh electronics toy 20 4 7
bash scripts/cross-domain/dann/maste.sh home book 5 0 7
bash scripts/cross-domain/dann/maste.sh beauty pet 20 3 7
bash scripts/cross-domain/dann/maste.sh electronics toy 20 0 7
bash scripts/cross-domain/dann/maste.sh fashion book 20 4 7
bash scripts/cross-domain/dann/maste.sh home book 20 3 7
bash scripts/cross-domain/dann/maste.sh electronics toy 5 0 7
bash scripts/cross-domain/dann/maste.sh electronics toy 10 3 7
bash scripts/cross-domain/dann/maste.sh home pet 5 1 7
bash scripts/cross-domain/dann/maste.sh beauty toy 20 2 7
bash scripts/cross-domain/dann/maste.sh all pet 3 0 7
bash scripts/cross-domain/dann/maste.sh fashion book 5 1 7
bash scripts/cross-domain/dann/maste.sh home pet 1 0 7
