bash scripts/cross-domain/dann/maste.sh beauty book 1 3 4
bash scripts/cross-domain/dann/maste.sh home grocery 10 0 4
bash scripts/cross-domain/dann/maste.sh beauty toy 5 1 4
bash scripts/cross-domain/dann/maste.sh home book 20 4 4
bash scripts/cross-domain/dann/maste.sh electronics pet 10 2 4
bash scripts/cross-domain/dann/maste.sh beauty grocery 10 3 4
bash scripts/cross-domain/dann/maste.sh all grocery 3 0 4
bash scripts/cross-domain/dann/maste.sh electronics pet 20 4 4
bash scripts/cross-domain/dann/maste.sh fashion grocery 20 0 4
bash scripts/cross-domain/dann/maste.sh fashion toy 1 4 4
bash scripts/cross-domain/dann/maste.sh home grocery 10 3 4
bash scripts/cross-domain/dann/maste.sh fashion grocery 3 4 4
bash scripts/cross-domain/dann/maste.sh beauty toy 3 1 4
bash scripts/cross-domain/dann/maste.sh fashion pet 5 2 4
bash scripts/cross-domain/dann/maste.sh home book 3 0 4
bash scripts/cross-domain/dann/maste.sh fashion toy 1 1 4
bash scripts/cross-domain/dann/maste.sh fashion book 3 4 4
bash scripts/cross-domain/dann/maste.sh beauty toy 20 0 4
bash scripts/cross-domain/dann/maste.sh beauty pet 1 4 4
bash scripts/cross-domain/dann/maste.sh electronics pet 20 2 4
bash scripts/cross-domain/dann/maste.sh fashion book 3 2 4
