bash scripts/cross-domain/dann/maste.sh home grocery 5 1 6
bash scripts/cross-domain/dann/maste.sh beauty pet 5 4 6
bash scripts/cross-domain/dann/maste.sh beauty grocery 3 0 6
bash scripts/cross-domain/dann/maste.sh home pet 3 3 6
bash scripts/cross-domain/dann/maste.sh all toy 5 2 6
bash scripts/cross-domain/dann/maste.sh electronics grocery 1 4 6
bash scripts/cross-domain/dann/maste.sh fashion grocery 10 0 6
bash scripts/cross-domain/dann/maste.sh electronics book 10 4 6
bash scripts/cross-domain/dann/maste.sh all grocery 1 3 6
bash scripts/cross-domain/dann/maste.sh electronics toy 3 1 6
bash scripts/cross-domain/dann/maste.sh fashion book 1 3 6
bash scripts/cross-domain/dann/maste.sh all grocery 10 0 6
bash scripts/cross-domain/dann/maste.sh fashion pet 5 1 6
bash scripts/cross-domain/dann/maste.sh beauty grocery 10 2 6
bash scripts/cross-domain/dann/maste.sh electronics book 1 1 6
bash scripts/cross-domain/dann/maste.sh electronics pet 10 0 6
bash scripts/cross-domain/dann/maste.sh home pet 1 3 6
bash scripts/cross-domain/dann/maste.sh fashion pet 20 1 6
bash scripts/cross-domain/dann/maste.sh home grocery 20 0 6
bash scripts/cross-domain/dann/maste.sh electronics pet 10 1 6
bash scripts/cross-domain/dann/maste.sh home pet 10 0 6
