bash scripts/cross-domain/dann/maste.sh beauty pet 3 2 7
bash scripts/cross-domain/dann/maste.sh fashion pet 3 2 7
bash scripts/cross-domain/dann/maste.sh all grocery 10 3 7
bash scripts/cross-domain/dann/maste.sh fashion pet 1 2 7
bash scripts/cross-domain/dann/maste.sh beauty toy 3 0 7
bash scripts/cross-domain/dann/maste.sh fashion grocery 5 4 7
bash scripts/cross-domain/dann/maste.sh home toy 5 1 7
bash scripts/cross-domain/dann/maste.sh beauty toy 10 3 7
bash scripts/cross-domain/dann/maste.sh beauty book 5 3 7
bash scripts/cross-domain/dann/maste.sh electronics toy 5 1 7
bash scripts/cross-domain/dann/maste.sh home toy 1 4 7
bash scripts/cross-domain/dann/maste.sh home pet 5 0 7
bash scripts/cross-domain/dann/maste.sh beauty book 1 4 7
bash scripts/cross-domain/dann/maste.sh electronics book 10 0 7
bash scripts/cross-domain/dann/maste.sh electronics pet 1 4 7
bash scripts/cross-domain/dann/maste.sh beauty book 20 3 7
bash scripts/cross-domain/dann/maste.sh fashion grocery 3 1 7
bash scripts/cross-domain/dann/maste.sh beauty grocery 1 0 7
bash scripts/cross-domain/dann/maste.sh all toy 1 3 7
bash scripts/cross-domain/dann/maste.sh all book 1 3 7
bash scripts/cross-domain/dann/maste.sh home book 10 3 7
