bash scripts/cross-domain/dann/maste.sh beauty book 5 1 1
bash scripts/cross-domain/dann/maste.sh fashion book 10 1 1
bash scripts/cross-domain/dann/maste.sh home grocery 10 1 1
bash scripts/cross-domain/dann/maste.sh electronics toy 5 4 1
bash scripts/cross-domain/dann/maste.sh all pet 3 3 1
bash scripts/cross-domain/dann/maste.sh electronics toy 3 0 1
bash scripts/cross-domain/dann/maste.sh all book 3 4 1
bash scripts/cross-domain/dann/maste.sh fashion toy 20 3 1
bash scripts/cross-domain/dann/maste.sh fashion toy 3 0 1
bash scripts/cross-domain/dann/maste.sh beauty pet 3 4 1
bash scripts/cross-domain/dann/maste.sh fashion toy 20 1 1
bash scripts/cross-domain/dann/maste.sh home toy 10 0 1
bash scripts/cross-domain/dann/maste.sh fashion pet 3 4 1
bash scripts/cross-domain/dann/maste.sh home pet 10 4 1
bash scripts/cross-domain/dann/maste.sh fashion pet 3 1 1
bash scripts/cross-domain/dann/maste.sh electronics book 5 0 1
bash scripts/cross-domain/dann/maste.sh home grocery 3 2 1
bash scripts/cross-domain/dann/maste.sh fashion grocery 5 1 1
bash scripts/cross-domain/dann/maste.sh electronics pet 5 3 1
bash scripts/cross-domain/dann/maste.sh all pet 5 0 1
bash scripts/cross-domain/dann/maste.sh beauty grocery 3 1 1
